### ISSUE TITLE
Abnormal termination on Docker failures

### ISSUE THREAD

**Issue by dberzano** [mconcas/plancton#116]
We've observed an abnormal behavior of Plancton on some nodes where Docker is for several reasons inoperative.

Here's the log excerpt: Plancton terminates with an exception.

Side effect: since the abnormal termination is caught by the daemon class the pidfile is removed and our automatic Plancton restarter does not start it back.

```
2016-12-16 19:38:09 root DEBUG [__init__._start_container] Starting 0f1c97047e748262aa3a9cb841f9d75b8a27d81b92bef80d18f530994981065c
2016-12-16 19:39:09 root WARNING [__init__.robust_call] [container_start], Failed to reach docker, retrying in 3 seconds.
2016-12-16 19:39:09 root WARNING [__init__.robust_call] UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-16 19:40:12 root WARNING [__init__.robust_call] [container_start], Failed to reach docker, retrying in 6 seconds.
2016-12-16 19:40:12 root WARNING [__init__.robust_call] UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-16 19:41:18 root WARNING [__init__.robust_call] [container_start], Failed to reach docker, retrying in 12 seconds.
2016-12-16 19:41:18 root WARNING [__init__.robust_call] UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-16 19:42:30 root WARNING [__init__.robust_call] [container_start], Failed to reach docker, retrying in 24 seconds.
2016-12-16 19:42:30 root WARNING [__init__.robust_call] UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-16 19:42:54 root ERROR [__init__.robust_call] Call [container_start] failed, after 5 tentatives.
2016-12-16 19:43:54 root ERROR [__init__._start_container] UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-16 19:44:54 root WARNING [__init__.robust_call] [container_list], Failed to reach docker, retrying in 3 seconds.
2016-12-16 19:44:54 root WARNING [__init__.robust_call] UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-16 19:45:57 root WARNING [__init__.robust_call] [container_list], Failed to reach docker, retrying in 6 seconds.
2016-12-16 19:45:57 root WARNING [__init__.robust_call] UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-16 19:47:04 root WARNING [__init__.robust_call] [container_list], Failed to reach docker, retrying in 12 seconds.
2016-12-16 19:47:04 root WARNING [__init__.robust_call] UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-16 19:48:16 root WARNING [__init__.robust_call] [container_list], Failed to reach docker, retrying in 24 seconds.
2016-12-16 19:48:16 root WARNING [__init__.robust_call] UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-16 19:48:40 root ERROR [__init__.robust_call] Call [container_list] failed, after 5 tentatives.
2016-12-16 19:49:40 root ERROR [__init__._control_containers] Couldn't get containers list: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-16 19:50:40 root WARNING [__init__.robust_call] [container_list], Failed to reach docker, retrying in 3 seconds.
2016-12-16 19:50:40 root WARNING [__init__.robust_call] UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-16 19:51:43 root WARNING [__init__.robust_call] [container_list], Failed to reach docker, retrying in 6 seconds.
2016-12-16 19:51:43 root WARNING [__init__.robust_call] UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-16 19:52:49 root WARNING [__init__.robust_call] [container_list], Failed to reach docker, retrying in 12 seconds.
2016-12-16 19:52:49 root WARNING [__init__.robust_call] UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-16 19:54:01 root WARNING [__init__.robust_call] [container_list], Failed to reach docker, retrying in 24 seconds.
2016-12-16 19:54:01 root WARNING [__init__.robust_call] UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-16 19:54:25 root ERROR [__init__.robust_call] Call [container_list] failed, after 5 tentatives.
2016-12-16 19:55:25 root ERROR [__init__._dump_container_list] Couldn't get container list: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2016-12-16 19:55:25 root ERROR [daemon.start] An exception occurred: traceback follows
Traceback (most recent call last):
  File "/var/lib/plancton/python/lib/python2.7/site-packages/plancton/daemon.py", line 158, in start
    self.run()
  File "/var/lib/plancton/python/lib/python2.7/site-packages/plancton/__init__.py", line 520, in run
    self.main_loop()
  File "/var/lib/plancton/python/lib/python2.7/site-packages/plancton/__init__.py", line 508, in main_loop
    self._dump_container_list()
  File "/var/lib/plancton/python/lib/python2.7/site-packages/plancton/__init__.py", line 315, in _dump_container_list
    for c in clist:
UnboundLocalError: local variable 'clist' referenced before assignment
2016-12-16 19:55:25 root CRITICAL [daemon.start] Terminating abnormally...
```

**Comment by dberzano** [comment]
@mconcas I am taking care of it, looks easy.

**Comment by dberzano** [comment]
@mconcas in any case good job with the "robust" machinery that handles timeouts 👍
