### ISSUE TITLE
Cannot start if Docker is down

### ISSUE THREAD

**Issue by dberzano** [mconcas/plancton#118]
Steps to reproduce:

1. Stop Docker: `systemctl stop docker`
2. Start Plancton: `planctonctl nodaemon`

Plancton will fail with:

```
Traceback (most recent call last):
  File "/home/dberzano/python/bin/planctonctl", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/dberzano/plancton/bin/planctonctl", line 63, in <module>
    rundir=rundir, confdir=confdir)
  File "/home/dberzano/plancton/plancton/__init__.py", line 138, in __init__
    self.docker_client = Client(base_url=self._sockpath, version="auto")
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 81, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 105, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', error(111, 'Connection refused'))
```

**Comment by dberzano** [comment]
This is slightly trickier. I am fixing it by introducing "lazy initialization" of the `self.docker_client` variable.

**Comment by dberzano** [comment]
@mconcas I am working on it
